version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
  mysql:
    image: mysql
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_data:
    driver: local