version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
  mysql:
    image: mysql
    env_file:
      - ./.env
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080